using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum ItemID
{
    NON_DROP_BLOCK = 9999,
    BEDROCK = 0,
    STONE_BLOCK = 1,
    GRASS_BLOCK = 2,
    COBBLESTONE_BLOCK = 3,
    SAND_BLOCK = 4,
    DIRT_BLOCK = 5,
    OAK_LOG = 6,
    OAK_PLANKS = 7,
    BRICKS_BLOCK = 8,
    GLASS_BLOCK = 9,
    OAK_LEAVES = 10,
    CACTUS_BLOCK = 11,
    COBBLESTONE_SLAB = 12,
    FURNANCE = 13,
    OAK_STAIRS = 14,
    COBBLESTONE_STAIRS = 15,
    WOOD_PICKAXE = 16,
    STONE_PICKAXE = 17,
    IRON_PICKAXE = 18,
    DIAMOND_PICKAXE = 19,
    WOOD_AXE = 20,
    STONE_AXE = 21,
    IRON_AXE = 22,
    DIAMOND_AXE = 23,
    CHEST = 24,
    COAL = 25,
    CHARCOAL = 26,
    COAL_ORE_BLOCK = 27,
    IRON_ORE_BLOCK = 28,
    DIAMOND_ORE_BLOCK = 29,
    IRON_INGOT = 30,
    DIAMOND = 31,
    OAK_SAPLING = 32,
    STICKS = 33,
    APPLE = 34,
    CRAFTING_TABLE = 35,
    CARROT = 36,
    POTATO = 37,
    BAKED_POTATO = 38,
    WHEAT = 39,
    BREAD = 40,
    WHEAT_SEEDS = 41,
    RAW_MUTTON = 42,
    COOKED_MUTTON = 43,
    WOOD_HOE = 44,
    STONE_HOE = 45,
    IRON_HOE = 46,
    DIAMOND_HOE = 47,
    ARROW = 48,
    BOW = 49,
    STRING = 50,
    BOSS_SUMMONER = 51
}
